"""Change expiration_date to Date

Revision ID: a0ac12680ede
Revises: 6f1d646fdc7a
Create Date: 2025-03-24 10:37:27.154523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ac12680ede'
down_revision = '6f1d646fdc7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('expiration_date',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('expiration_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
